# Global client configuration
globalClientConfigs:
  enableBuiltInMetrics: true
  healthCheckEndpoint: "127.0.0.1:8080"

# List of all listeners
listeners:
  - # Configuration for listener_1
    name: "listener_1"
    host: "127.0.0.1"
    port: 9042
    spanner:
      databaseUri: "projects/span-cloud-testing/instances/pecheverri-cassandra/databases/default"
      numGrpcChannels: 4
      maxCommitDelayMillis: 5
  - # Configuration for listener_2
    name: "listener_2"
    host: "127.0.0.2"
    port: 9043
    spanner:
      databaseUri: "projects/span-cloud-testing/instances/pecheverri-cassandra/databases/default"
      numGrpcChannels: 8
