name: Daily Integration Tests

on:
  schedule:
    - cron: '0 15 * * *' # Runs at 8:00 AM PST daily

jobs:
  daily_integration_run_prod:
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit
  
  # Because GitHub does not support passing env vars directly to reusable work
  env_vars_for_devel:
    runs-on: ubuntu-latest
    outputs:
      SPANNER_ENDPOINT: ${{secrets.SPANNER_DEVEL_ENDPOINT}}
    steps:
      - run: echo "Exposing env var"
  
  daily_integration_run_devel:
    needs: [env_vars_for_devel]
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit
    with:
      SPANNER_ENDPOINT: ${{needs.env_vars_for_devel.outputs.SPANNER_ENDPOINT}}
    
  notify_on_failure:
    runs-on: ubuntu-latest
    needs: [daily_integration_run_prod, daily_integration_run_devel]
    if: failure()
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            if ('${{ needs.daily_integration_run_prod.result }}' === 'failure') {
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🚨 [PROD] Daily integration tests against prod failed!',
                body: `See [failed job](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
              });
            }
            if ('${{ needs.daily_integration_run_devel.result }}' === 'failure') {
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🚨 [DEVEL] Daily integration tests against devel failed!',
                body: `See [failed job](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
              });
            }
