name: Integration Tests

on:
  workflow_call:
    secrets:
      SPANNER_CASSANDRA_ADAPTER_CICD_SERVICE_ACCOUNT:
        required: true
      INTEGRATION_TEST_INSTANCE:
        required: true
    inputs:
      SPANNER_ENDPOINT:
        description: 'The Spanner endpoint to target'
        required: false
        type: string
        default: "spanner.googleapis.com:443"

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.SPANNER_CASSANDRA_ADAPTER_CICD_SERVICE_ACCOUNT }}'
    - run: java -version
    - run: .kokoro/build.sh
      env:
        JOB_TYPE: integration
        INTEGRATION_TEST_INSTANCE: ${{secrets.INTEGRATION_TEST_INSTANCE}}
        SPANNER_ENDPOINT: ${{ inputs.SPANNER_ENDPOINT }}
